### ISSUE TITLE
error with setup (Kali Linux)

### ISSUE THREAD

**Issue by TrunksDeDBZ** [aithedev/TikTok-Account-Generator#16]
ERROR: Could not find a version that satisfies the requirement ptyz (from versions: none)
ERROR: No matching distribution found for ptyz

**Comment by TrunksDeDBZ** [comment]
Traceback (most recent call last):
  File "/root/TikTok-Account-Generator/main.py", line 4, in <module>
    from utils.api import *
  File "/root/TikTok-Account-Generator/utils/api.py", line 15, in <module>
    from Terminalia import Terminal
ModuleNotFoundError: No module named 'Terminalia'

**Comment by aithedev** [comment]
bro
