### ISSUE TITLE
error in getting mails

### ISSUE THREAD

**Issue by tahfinarehman06** [aithedev/TikTok-Account-Generator#20]
full log:

~/.../downloads/tikk $ python3 main.py
Number of accounts to register: 3
Threads: 1
Exception in thread Thread-1 (register):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/emulated/0/Download/tikk/main.py", line 178, in register
    messages = Email().get_mail(email)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Download/tikk/utils/api.py", line 53, in get_mail
    if base_mail.json()["emails"] == []:
       ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by aithedev** [comment]
yeah the site is down
